### ISSUE TITLE
Unfortunately its difficult system

### ISSUE THREAD

**Issue by rgleason** [opencpn-manuals/plugins#62]
I have had many losses of changes/commits due to failures not of my making and recently overwriting of edits committed to build that were not reviewed and accepted.
https://github.com/Rasbats/calculator_pi/pull/7

For **Internal Plugins** should I just use the **Edit this Page** button and commit to **Main**  after committing to **Build** and viewing the changes?     Also do other git users have access to the "Edit this Page" button for Internal Plugins?  Who is reviewiing their commitss to "Build".  Do they also have to commit to "Main"?  How are they to know that?

Unfortunately I am not going to spend another day editing until the separate processes as noted in the link above are sorted out  and a workiing process can be enumerated for each type of edit needed.  Sorry, it is just not worth doing.

**Comment by rgleason** [comment]
I guess I am going to go back to working on plugins now which need lots of work.

By the time this is sorted out I will have forgotten the changes I made, but it is possible that the build branch still has those changes and they can be recovered and pushed to main?

**Comment by rgleason** [comment]
The are changes here that I need to get into main
https://github.com/opencpn-manuals/plugins/commits/build

Dashboard changes
https://github.com/opencpn-manuals/plugins/commit/307a255db83cb365c434ccc6554c9ccca5301ddf

Grib Weather changes
[Update grib_weather.adoc Links ](https://github.com/opencpn-manuals/plugins/commit/2ba0e5bbf8c59f799b8b68a66cfb6c297ed4d7b9)
and 
https://github.com/opencpn-manuals/plugins/commit/936c78f754d1a4ca809e419848a178fda50b407e

But I don't find all my other changes to grib_pi formatting, gone into thin air.  Why? I thought git kept a complete history..

In dokuwiki I just make the XXXXing changes and SAVE.  This is a tremendous waste of time and I am beginning to dislike it.

**Comment by Rasbats** [comment]
> workiing process can be enumerated for each type of edit is needed

Agree. Time. I need to experiment with "Edit this page" for the main manual and see what the problem is. 
Build branch is a dustbin used for creating gh-pages. Stuff should not be pushed to build.

For editing the main manual stuff Visual Studio Code works well. I have not tried  "Edit this page" for that stuff yet.

 "Edit this page" for the included plugins from the website page takes you to the build branch because that is where the gh-pages come from. The other plugins are built from the original dev source repo so that is where  "Edit this page" leads for those pages.

**Comment by rgleason** [comment]
Do we want any Github user to be able to hit Edit this page for the Internal Plugins and then commit to Main?  NO.
All the plugins have a filter person reviewing.
How can we get this to work?   Make another branch Internal-PI that Git Users commit to. Then someone has to review them commiits and accept to "Main" via some process that hopefully is completely clear and defined.

I am editing in whatever, freehand using the git edit button etc.  using Notepad ++ at times, I was using VScode but the changes are pretty simple

**Comment by Rasbats** [comment]
Ok Rick ... I have merged all you work on Grib and Dashboard.

**Comment by Rasbats** [comment]
If you look at the bottom of  the page after pressing "Edit this page" you will see another option. Follow this along and you get the option to make a PR to the main branch. Then delete the temporary branch.

**Comment by rgleason** [comment]
Jees, learning. software,  that is great, but I still don't find my earlier commit to build that must have gotten overwritten. It was primarily about getting  Grib_pi in a similar format to the original.... 

I will look more carefully, but the normal Git User won't get this either and we need a person filter anyway to accept changes like we have for the other plugins.

Thanks!

**Comment by rgleason** [comment]
Well, I kind of got there round about..... I made changes and did not find it quite as you describe
https://github.com/opencpn-manuals/plugins/pull/64/

Hope they are ok.

**Comment by Rasbats** [comment]
`Update Dashboard.adoc small format changes` came through.
You won't see those changes until you pull them to your clone and `git push -f origin main:build`

**Comment by Rasbats** [comment]
> git push -f origin main:build

Done. Perhaps check that the Grib and Dashboard stuff got through.

**Comment by rgleason** [comment]
I was able to push to main after some rig amarole, but in the process I saved the adoc to a  .adoc.backup  then renamed it and tried to push to main and it allowed that  all from within that Edit this page interface ---> git interface.  That process sure isn't clean and Alec will have some reason it is terrible to do.

**Comment by leamas** [comment]
@rgleason : See https://github.com/opencpn-manuals/plugins/issues/61#issuecomment-922533818

**Comment by leamas** [comment]
> For editing the main manual stuff Visual Studio Code works well.

In other words: avoiding Edit This Page like mentioned din  https://github.com/opencpn-manuals/plugins/issues/61#issuecomment-922533818 is the way to go.

> Edit this page" for the included plugins from the website page takes you to the build branch because that is where the gh-pages come from.

This is a plain bug we need to handle, either by fixing the link or by just removing it. Filed #65 

@rasbats: Good catch!

**Comment by leamas** [comment]
> Do we want any Github user to be able to hit Edit this page for the Internal Plugins and then commit to Main? 

See #65

**Comment by rgleason** [comment]
I caught it too and save the rest of my work after doing it for the 2nd time
https://github.com/opencpn-manuals/plugins/commit/c8f6d1cf343d35daa6f500d2baaa39ab645fe0f4

**Comment by leamas** [comment]
As for the heading, we have yet not seen much questions about "the system".  What we are dealing with is mostly problems with how to handle git, and to some lesser extent how to handle the sources and source-state.sh.

That is, the summary of this issue (what *is* the issue?) is IMHO misleading.

**Comment by rgleason** [comment]
Dokuwiki " Save"  vs  Github   process...  Closing.  We are committed to github now. Not fruitful, but useful.
